# Generated by Django 4.2 on 2023-04-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
