# Generated by Django 4.2 on 2023-04-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_cards_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
