# Generated by Django 4.2.1 on 2023-05-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='categoria',
        ),
        migrations.AddField(
            model_name='cards',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodCat', to='myapp.categoria'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombreCate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
