# Generated by Django 4.2.1 on 2023-05-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_categoria_categoria_cards_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nombreCate',
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
